title: Sarat Bhargava
author: saratbhargava
email: sarat2895@gmail.com
description: Machine learning engineer

theme: minima

# social links
twitter_username: SaratChinni
github_username:  saratbhargava

show_excerpts: true # set to false to remove excerpts on the homepage
